CREATE TABLE IF NOT EXISTS wechat_compositions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  org_id INT NULL,
  name VARCHAR(120) NOT NULL,
  title VARCHAR(255) NULL,
  digest VARCHAR(512) NULL,
  doc MEDIUMTEXT NOT NULL,
  block_config TEXT NULL,
  theme_key VARCHAR(32) NULL,
  block_count INT NOT NULL DEFAULT 0,
  image_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_user (user_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
