-- scripts/create_ai_tables.sql

CREATE TABLE IF NOT EXISTS ai_jobs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NULL,
  project_id BIGINT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  model VARCHAR(128) DEFAULT NULL,
  prompt_text LONGTEXT,
  options JSON NULL,
  client_request_id VARCHAR(255) NULL,
  tokens_used BIGINT NULL,
  cost_estimate DECIMAL(18,6) NULL,
  error TEXT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (user_id),
  INDEX (project_id),
  INDEX (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_results (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  job_id BIGINT NOT NULL,
  title VARCHAR(255) DEFAULT NULL,
  subtitle VARCHAR(255) DEFAULT NULL,
  markdown LONGTEXT,
  html LONGTEXT,
  placeholders JSON NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_templates (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  org_id BIGINT NULL,
  name VARCHAR(255) NOT NULL,
  template_text LONGTEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_audit_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  job_id BIGINT NULL,
  action VARCHAR(255),
  actor VARCHAR(255),
  note TEXT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
